# settings.yaml - ไฟล์นี้ไม่มีเส้นทางจริงในโปรเจค แต่เป็นตัวอย่างเพื่อการเตรียมพร้อมในอนาคต
paths:
  /api/users/{userId}/settings:
    get:
      tags:
        - Users
      summary: Get user settings
      description: Get user settings and preferences
      operationId: getUserSettings
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Settings retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'