# user-api.yaml - ไฟล์รวมสำหรับ API ผู้ใช้งานทั่วไป
openapi: 3.0.0
info:
  title: CSI Showcase - User API
  description: API documentation for CSI Showcase - Student Project Showcase Platform
  version: 1.0.0
  contact:
    name: CSI Admin Team
    email: admin@csi-showcase.example.com

servers:
  - url: http://localhost:5000
    description: Development server
  - url: https://api.csi-showcase.example.com
    description: Production server

tags:
  - name: Authentication
    description: Operations about user authentication
  - name: Users
    description: Operations about users
  - name: Projects
    description: Operations about projects
  - name: Search
    description: Search operations
  - name: Upload
    description: File upload operations

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

# นำเข้าโครงสร้างข้อมูล
  schemas:
    # ส่วนของ schemas จาก common.yaml
    SuccessResponse:
      $ref: './schemas/common.yaml#/components/schemas/SuccessResponse'
    ErrorResponse:
      $ref: './schemas/common.yaml#/components/schemas/ErrorResponse'
    ValidationErrorResponse:
      $ref: './schemas/common.yaml#/components/schemas/ValidationErrorResponse'
    PaginationInfo:
      $ref: './schemas/common.yaml#/components/schemas/PaginationInfo'

    # ส่วนของ schemas จาก user.yaml
    User:
      $ref: './schemas/user.yaml#/components/schemas/User'
    UserProfile:
      $ref: './schemas/user.yaml#/components/schemas/UserProfile'
    UserStats:
      $ref: './schemas/user.yaml#/components/schemas/UserStats'

    # ส่วนของ schemas จาก project.yaml
    Project:
      $ref: './schemas/project.yaml#/components/schemas/Project'
    ProjectDetails:
      $ref: './schemas/project.yaml#/components/schemas/ProjectDetails'
    ProjectFile:
      $ref: './schemas/project.yaml#/components/schemas/ProjectFile'
    ProjectContributor:
      $ref: './schemas/project.yaml#/components/schemas/ProjectContributor'
    ProjectStats:
      $ref: './schemas/project.yaml#/components/schemas/ProjectStats'

    # ส่วนของ schemas จาก request-bodies.yaml
    LoginRequest:
      $ref: './schemas/request-bodies.yaml#/components/schemas/LoginRequest'
    RegisterRequest:
      $ref: './schemas/request-bodies.yaml#/components/schemas/RegisterRequest'
    ForgotPasswordRequest:
      $ref: './schemas/request-bodies.yaml#/components/schemas/ForgotPasswordRequest'
    ResetPasswordRequest:
      $ref: './schemas/request-bodies.yaml#/components/schemas/ResetPasswordRequest'
    ChangePasswordRequest:
      $ref: './schemas/request-bodies.yaml#/components/schemas/ChangePasswordRequest'
    UpdateUserRequest:
      $ref: './schemas/request-bodies.yaml#/components/schemas/UpdateUserRequest'

# นำเข้าเส้นทางทั้งหมด
paths:
  # ส่วนของ auth
  /api/auth/login:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1login'
  /api/auth/register:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1register'
  /api/auth/forgot-password:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1forgot-password'
  /api/auth/reset-password:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1reset-password'
  /api/auth/verify-token:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1verify-token'
  /api/auth/me:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1me'
  /api/auth/logout:
    $ref: './paths/auth/user-auth.yaml#/paths/~1api~1auth~1logout'

  # ส่วนของ user
  /api/users/{userId}:
    $ref: './paths/user/profile.yaml#/paths/~1api~1users~1{userId}'
  /api/users/{userId}/change-password:
    $ref: './paths/user/profile.yaml#/paths/~1api~1users~1{userId}~1change-password'
  /api/users/{userId}/settings:
    $ref: './paths/user/settings.yaml#/paths/~1api~1users~1{userId}~1settings'

  # ส่วนของ project
  /api/projects:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects'
  /api/projects/top:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1top'
  /api/projects/latest:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1latest'
  /api/projects/user/{userId}:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1user~1{userId}'
  /api/projects/{projectId}:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1{projectId}'
  /api/projects/{projectId}/files:
    $ref: './paths/project/project-files.yaml#/paths/~1api~1projects~1{projectId}~1files'
  /api/projects/{projectId}/visitor-view:
    $ref: './paths/project/project-views.yaml#/paths/~1api~1projects~1{projectId}~1visitor-view'
  /api/projects/{projectId}/company-view:
    $ref: './paths/project/project-views.yaml#/paths/~1api~1projects~1{projectId}~1company-view'
  /api/projects/types:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1types'
  /api/projects/years:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1years'
  /api/projects/study-years:
    $ref: './paths/project/project-crud.yaml#/paths/~1api~1projects~1study-years'

  # ส่วนของ search
  /api/search/projects:
    $ref: './paths/search/search.yaml#/paths/~1api~1search~1projects'
  /api/search/users:
    $ref: './paths/search/search.yaml#/paths/~1api~1search~1users'

  # ส่วนของ upload
  /api/upload/profile-image:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1profile-image'
  /api/upload/images:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1images'
  /api/upload/video:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1video'
  /api/upload/documents:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1documents'
  /api/upload/files:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1files'
  /api/upload/multiple:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1multiple'
  /api/upload/delete:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1delete'
  /api/upload/storage-status:
    $ref: './paths/upload/uploads.yaml#/paths/~1api~1upload~1storage-status'